name: docker_test_env

dependencies:
  - python=3.7
  - psycopg2=2.8
  - pip=21.0
  - pip:
      - Django==3.1
      - gunicorn==20.0
      - drf-yasg==1.20
      - Pillow==8.1
      - djangorestframework==3.12
      - djangorestframework-simplejwt==4.6
      - flake8==3.9
