name: docker_test_env

dependencies:
  - python==3.7
  - psycopg2
  - pip:
      - Django
      - gunicorn
      - drf-yasg
      - Pillow
      - djangorestframework
      - djangorestframework-simplejwt
      - flake8
