<<<<<<< HEAD
# Generated by Django 3.1 on 2021-03-25 09:35

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.1 on 2021-03-25 08:39

from django.db import migrations, models
>>>>>>> c84e6a8fc055e7a0be38e77471247e5874438445


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('userprofile', '0001_initial'),
=======
>>>>>>> c84e6a8fc055e7a0be38e77471247e5874438445
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('changed_when', models.DateTimeField(auto_now=True)),
                ('created_when', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('liked_by', models.ManyToManyField(blank=True, related_name='userprofile', to='userprofile.Userprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to='userprofile.userprofile')),
=======
>>>>>>> c84e6a8fc055e7a0be38e77471247e5874438445
            ],
        ),
    ]
