<<<<<<< HEAD
# Generated by Django 3.1 on 2021-03-25 09:35

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.1 on 2021-03-25 08:39

from django.db import migrations, models
>>>>>>> c84e6a8fc055e7a0be38e77471247e5874438445


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('userprofile', '0001_initial'),
=======
>>>>>>> c84e6a8fc055e7a0be38e77471247e5874438445
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('P', 'Pending')], default='P', max_length=1)),
                ('resolved_time', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('received_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='userprofile.userprofile')),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='userprofile.userprofile')),
=======
>>>>>>> c84e6a8fc055e7a0be38e77471247e5874438445
            ],
        ),
    ]
