<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.1 on 2021-03-25 09:35

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.1 on 2021-03-25 08:39
=======
# Generated by Django 3.1 on 2021-03-25 13:05
>>>>>>> 4ca47d76ed9da0a94e3bd3268f4b421affc0ada6

from django.db import migrations, models
>>>>>>> c84e6a8fc055e7a0be38e77471247e5874438445


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('post', '0001_initial'),
        ('userprofile', '0001_initial'),
=======
>>>>>>> c84e6a8fc055e7a0be38e77471247e5874438445
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('changed_when', models.DateTimeField(auto_now=True)),
                ('created_when', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('comment_on_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='userprofile.userprofile')),
=======
>>>>>>> c84e6a8fc055e7a0be38e77471247e5874438445
            ],
        ),
    ]
